version: '2'
services:
  mastodon-web:
    restart: always
    image: gilir/arm64-mastodon
    container_name: mastodon-web
    env_file: .env.production
    ports:
      - "3000:3000"
#      - "4000:4000"
    networks:
      - proxy-network
    volumes:
      - mastodon_public_assets:/mastodon/public/assets
      - mastodon_public_packs:/mastodon/public/packs
      - mastodon_public_system:/mastodon/public/system
      - mastodon_log:/mastodon/log
    labels:
      - traefik.frontend.rule=Host:mastodon.lavergne.online
      - traefik.docker.network=proxy-network
      - traefik.port=3000
      - traefik.backend=mastodon-web
      - traefik.frontend.entryPoints=https,http
    environment:
      - WEB_CONCURRENCY=1
      - MAX_THREADS=5
      - SIDEKIQ_WORKERS=5
      - RUN_DB_MIGRATIONS=true
      - RAILS_SERVE_STATIC_FILES=false

networks:
  proxy-network:
    external:
      name: proxy-network

volumes:
  mastodon_public_assets:
    external: true
  mastodon_public_system:
    external: true
  mastodon_public_packs:
    external: true
  mastodon_log:
    external: true
