version: '2'
services:
  mastodon-web:
    restart: always
    image: gilir/arm64-mastodon
    container_name: mastodon-web
    env_file: .env.production
    ports:
      - "3000:3000"
      - "4000:4000"
    networks:
      - proxy-network
    volumes:
      - mastodon_public_assets:/mastodon/public/assets
      - mastodon_public_packs:/mastodon/public/packs
      - mastodon_public_system:/mastodon/public/system
      - mastodon_log:/mastodon/log
    labels:
      - traefik.main.frontend.rule=Host:mastodon.lavergne.online
      - traefik.main.docker.network=proxy-network
      - traefik.main.port=3000
      - traefik.main.backend=mastodon-web
      - traefik.main.frontend.entryPoints=https,http
      - traefik.stream.frontend.rule=Host:mastodon.lavergne.online;PathPrefixStrip:/api/v1/streaming
      - traefik.stream.docker.network=proxy-network
      - traefik.stream.port=4000
      - traefik.stream.backend=mastodon-streaming
      - traefik.stream.frontend.entryPoints=https,http
    environment:
      - WEB_CONCURRENCY=1
      - MAX_THREADS=5
      - SIDEKIQ_WORKERS=5
      - RUN_DB_MIGRATIONS=true
      - RAILS_SERVE_STATIC_FILES=false

networks:
  proxy-network:
    external:
      name: proxy-network

# Simple volume mapped to a local directory /path/to/data :
# docker volume create --opt type=none --opt device=/path/to/data --opt o=bind --name name_of_the_volume
volumes:
  mastodon_public_assets:
    external: true
  mastodon_public_system:
    external: true
  mastodon_public_packs:
    external: true
  mastodon_log:
    external: true
