version: '2'
services:
  db:
    restart: always
    image: armhf/postgres:9.6-alpine
    container_name: mastodon-db
    networks:
      - proxy-network
    volumes:
      - mastodon_postgres:/var/lib/postgresql/data
    labels:
      - "traefik.enable=false"
  redis:
    restart: always
    image: armhf/redis
    container_name: mastodon-redis
    command: redis-server --appendonly yes
    networks:
      - proxy-network
    volumes:
      - mastodon_redis:/data
    labels:
      - "traefik.enable=false"

  mastodon-web:
    restart: always
    build: .
    image: gilir/rpi-mastodon
    container_name: mastodon-web
    env_file: .env.production
    ports:
      - "3000:3000"
      - "4000:4000"
    depends_on:
      - db
      - redis
    networks:
      - proxy-network
    volumes:
      - mastodon_public_assets:/mastodon/public/assets
      - mastodon_public_packs:/mastodon/public/packs
      - mastodon_public_system:/mastodon/public/system
      - mastodon_log:/mastodon/log
    labels:
      - "traefik.docker.network=proxy-network"
      - "traefik.backend=mastodon-web"
      - "traefik.port=3000"
      - "traefik.frontend.rule=Host:mastodon.lavergne.online"
    environment:
      - WEB_CONCURRENCY=1
      - MAX_THREADS=5
      - SIDEKIQ_WORKERS=5
      - RUN_DB_MIGRATIONS=true

networks:
  proxy-network:
    external:
      name: proxy-network

volumes:
  mastodon_postgres:
    external: true
  mastodon_redis:
    external: true
  mastodon_public_assets:
    external: true
  mastodon_public_system:
    external: true
  mastodon_public_packs:
    external: true
