version: '2'
services:
  mastodon-db:
    restart: always
    image: arm64v8/postgres:9.6
    container_name: mastodon-db
    networks:
      - proxy-network
    volumes:
      - mastodon_postgres:/var/lib/postgresql/data
    labels:
      - "traefik.enable=false"

networks:
  proxy-network:
    external:
      name: proxy-network

volumes:
  mastodon_postgres:
    external: true
